backend:
  name: github
  repo: ddcech/ddcech.github.io
  branch: "master"
collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "LandingPage"
        name: "landing"
        file: "src/pages/landing.json"
        fields:
          - {label: PageName, name: pageName, widget: hidden, default: "landing"}
          - {label: Title, name: title, widget: string}
          - {label: Intro, name: intro, widget: string}
          - {label: Quote, name: quote, widget: string}
          - {label: About, name: about, widget: markdown}
          - label: "Social Links"
            name: "social"
            widget: "list"
            fields:
            - label: Network
              name: network
              widget: object
              fields:
                - {label: Link, name: link, widget: string}
                - label: Key
                  name: key
                  widget: select
                  options:
                  - { label: "Facebook", value: "facebook" }
                  - { label: "Instagram", value: "instagram" }
                  - { label: "LinkedIn", value: "linkedin" }
media_folder: static/img
public_folder: /img