backend:
  name: github
  repo: ddcech/ddcech.github.io
  branch: "master"
collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "LandingPage"
        name: "landing"
        file: "src/pages/landing.json"
        fields:
          - {label: PageName, name: pageName, widget: hidden, default: "landing"}
          - {label: Title, name: title, widget: string}
          - {label: Intro, name: intro, widget: string}
          - {label: Quote, name: quote, widget: string}
          - {label: About, name: about, widget: markdown}
          - label: "Social Links"
            name: "social"
            widget: "list"
            fields:
            - {label: Quote, name: quote, widget: string, default: "Everything is awesome!"}
            # - label: Author
            #   name: author
            #   widget: object
            #   fields:
            #     - {label: Name, name: name, widget: string}
media_folder: static/img
public_folder: /img